main: craftswitcher.CraftSwitcherPlugin
name: CraftSwitcher
version: 2.0.0b/240812
dncore: 6.0.0
description: "Minecraftサーバーの監視と管理を行うdnCoreプラグイン"

authors:
  - Necnion8

libraries:
  - psutil
  - fastapi
  - uvicorn
  - websockets
  - python-multipart
  - sqlalchemy
  - aiosqlite
  - passlib
  - bcrypt
  - pywinpty; sys_platform == "win32"
  - pydantic
  - aiohttp
  - watchdog
  - croniter
